In [9]:
# 167 重点
class Solution:
    def twoSum(self, x, target): #设置两个指针m,n   m+n=9
        sorted(x)
        flag=1
        m=0
        n=len(x)-1
        index=[]
        while flag:
            if len(x)!=0:break
            if m+n>target:n-=1
            elif m+n<target:m+=1
            elif m+n==target:
                index.append(m)
                index.append(n)
        return index
            

In [91]:
#215  大顶堆
# 先按照下标建立一颗树，完全二叉树，就是左边总是满的
#根为1，于是一个点n，他的左孩子： 2n   右孩子2n+1
# 这里是根为0   节点n  左孩子 2n+1  右孩子2n+2
nums=[1,6,3,8,5,4,2,22,100,122,133]


class Solution:
    def twoSum(self, nums, k):
        return self.heap_sort(nums,k)
        
    #构建大顶堆
    def heap_sort(self,nums,k): #负责把顶绕到list的最后
        for i in range(len(nums)//2-1,-1,-1): #遍历起点：最尾一个父节点，一直到0，就是根
            self.heap_adjust(nums,i,len(nums)) #处理第i个父节点
            #在内类，这个nums为全局变量
        #第二步就是把顶元素和末尾元素进行互换，使得末尾元素最大，因为已经保证了前面的都是大元素
        cnt = 0 #count 计数器
        for i in range(len(nums)-1,0,-1):  #从最末未到1
            self.heap_swap(nums,0,i)#0和i互换
            cnt+=1
            if cnt==k:#只要排好K个就好了，而且返回第K个
                return nums[i]
            self.heap_adjust(nums,0,i)#还没到的话，就继续查看 父和子的关系
            
        return nums[len(nums)-k]
    
    def heap_adjust(self,nums,start,length):#负责把大的值传给父节点
        print('取得的条件:',start,length)
        tmp=nums[start] #取得父节点value
        k=start*2+1 #左孩子
        while k<length: #
            left=start*2+1
            right=left+1
            if right<length and nums[right]>nums[left]: #左右孩子取大的，
                k=right
            if nums[k]>tmp: #大孩子与父亲比
                nums[start]=nums[k]#父节点取这个大孩子
                start=k #然后以k为父节点
            else:
                break
            k=k*2+1 #k取新的左孩子  这时候超出长度了
        print('tmp:',tmp)
        nums[start]=tmp
        print(nums)
    def heap_swap(self,nums,i,j):#互换
        nums[i],nums[j]=nums[j],nums[i]
        return nums

exam=Solution()

print(exam.twoSum(nums,4))

取得的条件: 4 11
tmp: 5
[1, 6, 3, 8, 133, 4, 2, 22, 100, 122, 5]
取得的条件: 3 11
tmp: 8
[1, 6, 3, 100, 133, 4, 2, 22, 8, 122, 5]
取得的条件: 2 11
tmp: 3
[1, 6, 4, 100, 133, 3, 2, 22, 8, 122, 5]
取得的条件: 1 11
tmp: 6
[1, 133, 4, 100, 122, 3, 2, 22, 8, 6, 5]
取得的条件: 0 11
tmp: 1
[133, 122, 4, 100, 6, 3, 2, 22, 8, 1, 5]
取得的条件: 0 10
tmp: 5
[122, 100, 4, 22, 6, 3, 2, 5, 8, 1, 133]
取得的条件: 0 9
tmp: 1
[100, 22, 4, 8, 6, 3, 2, 5, 1, 122, 133]
取得的条件: 0 8
tmp: 1
[22, 8, 4, 5, 6, 3, 2, 1, 100, 122, 133]
22


In [27]:
nums=[1,6,3,8,5,4,2]
class Solution:
    def stack_sort(self, nums, k):
        for i in range(len(nums)):
            

SyntaxError: unexpected EOF while parsing (<ipython-input-27-0fd48a7191d5>, line 5)

In [104]:
#215快排序 
nums=[3,2,10,1,9,4,7,6]
class Solution:
    def findKthLargest(self, nums, k):
        return self.quick_sort(nums,k)
    def quick_sort(self,nums,k):
        k=len(nums)-k   #我要的是这一位，如果这里拍好了，就可以了
        left=0
        right=len(nums)-1 #全局初始化左右指针
        while left<right:#直到全局 交叉
            j=self.partition(nums,left,right)
            if j==k:
                break
            elif j<k:
                left=j+1
            else:
                right=j-1
        print(nums)
        return nums[k]
    def partition(self,nums,left,right):
        while True:
            while nums[left]<nums[right]:
                right-=1
            nums[left],nums[right]=nums[right],nums[left]
            if left>=right:#交叉
                break
            right-=1
        return left
a=Solution()
a.findKthLargest(nums,4)

[1, 2, 3, 4, 6, 7, 9, 10]


6

In [43]:
def QuickSort(myList,start,end):
    #判断low是否小于high,如果为false,直接返回
    if start < end:
        i,j = start,end
        #设置基准数
        base = myList[i]

        while i < j:
            #如果列表后边的数,比基准数大或相等,则前移一位直到有比基准数小的数出现
            while (i < j) and (myList[j] >= base):
                j = j - 1
                
            #如找到,则把第j个元素赋值给第个元素i,此时表中i,j个元素相等
            #myList[i],myList[j] = myList[j],myList[i]
            print('j:',myList)
            #同样的方式比较前半区
            while (i < j) and (myList[i] <= base):
                i = i + 1
            myList[i],myList[j] = myList[j],myList[i] #全局变量list改变了
            print('i',myList)
        #做完第一轮比较之后,列表被分成了两个半区,并且i=j,需要将这个数设置回base
        
        myList[i],myList[start] = base,myList[i]
        
        
        #递归前后半区
        QuickSort(myList, start, i - 1) #在末尾的递归，因为i=j所以直接pass，不满足所有while
        QuickSort(myList, j + 1, end) #传入myList ，修改就相当于指针指的值修改
#改变数组值的一般不同返回值，如果没有数组的，一般都要返回


In [44]:
myList = [49,38,65,97,76,13,27,49]
print("Quick Sort: ")
QuickSort(myList,0,len(myList)-1)
print(myList)

Quick Sort: 
j: [49, 38, 65, 97, 76, 13, 27, 49]
i [49, 38, 27, 97, 76, 13, 65, 49]
j: [49, 38, 27, 97, 76, 13, 65, 49]
i [49, 38, 27, 13, 76, 97, 65, 49]
j: [49, 38, 27, 13, 76, 97, 65, 49]
i [49, 38, 27, 13, 76, 97, 65, 49]
j: [13, 38, 27, 49, 76, 97, 65, 49]
i [13, 38, 27, 49, 76, 97, 65, 49]
j: [13, 38, 27, 49, 76, 97, 65, 49]
i [13, 38, 27, 49, 76, 97, 65, 49]
j: [13, 27, 38, 49, 76, 97, 65, 49]
i [13, 27, 38, 49, 76, 49, 65, 97]
j: [13, 27, 38, 49, 76, 49, 65, 97]
i [13, 27, 38, 49, 76, 49, 65, 97]
j: [13, 27, 38, 49, 65, 49, 76, 97]
i [13, 27, 38, 49, 65, 49, 76, 97]
[13, 27, 38, 49, 49, 65, 76, 97]


In [11]:
# 频次前K高的元素  桶排序

nums=[1,1,1,2,2,3]
k=2
class Solution:
    
    def high_appearance(self, nums, k):
        self.nums=nums
        dic={}
        for i in self.nums:
            dic[i]=dic.get(i,0)+1
#         建立桶
        buc=[[] for i in range(len(self.nums))]
        for key,value in dic.items():
            
            buc[value].append(key)  #行为频次，最下面的行，为最高频次，所以依次输出
        print(buc)
        result=[]
        for x in range(len(self.nums)-1,-1,-1):#从尾到前遍历buc\
            print(buc[x])
            if k>0 and buc[x]:
                result.extend(buc[x]) #
                k-=len(buc[x])
            if k==0:
                return result
        
exam=Solution()
a,b=exam.high_appearance(nums,2)
a,b
# print(a.values())
# print(a.keys())
# print(a)

# self变量必须在self函数里面定义，初始化也行

[[], [3], [2], [1], [], []]
[]
[]
[1]
[2]


(1, 2)

In [41]:
# 75 颜色分类
# 
# 0，1，2代表红白蓝
# 可以用桶排序的方法，按照0,1,2先后顺序，按照对应频次append进result
nums=[2,0,2,1,1,0]
# 输出 [0,0,1,1,2,2]
class Solution:
    def sortColors(self, nums):
        dic1={}
        big=0
        for i in nums:
            dic1[i]=dic1.get(i,0)+1
            if i>big:big=i
        buc=[[] for j in range(big+1)] #这里其实应该要建立 nums中最大数字 个长度
        result=[]
        for key,val in dic1.items():
            buc[key].append(val)
        for i in range(len(buc)):
            if buc[i]:
                print(buc[i])
                for j in range(buc[i][0]):  #i是颜色，buc[i]是频次
                    result.append(i)
        
        for i in range(len(result)):#注意 nums=result的话是不行的 ，不能改变全局变量
            nums[i]=result[i]
        return result
        
        
        
exam=Solution()
exam.sortColors(nums)
nums

[2]
[2]
[2]


[0, 0, 1, 1, 2, 2]

In [18]:
a=[]#空list会返回False
if a:
    print('True')

In [42]:
#方法二:
#1、 定义三个指针  指针i代表当前遍历到的元素   zeroIndex代表当前0元素最大下标的指针（也就是0元素末尾下标）  twoIndex代表当前2元素最小的下标（也就是2元素开头的下标）
#2、 遇到0、2则和当前nums[i]交换 更新维护各个指针的值   
#3、 注意两个点 点1 当nums[i]==2 是把它交换到了元素2的开头  所以从twoIndex到数组末尾都是遍历过的元素，所以while结束条件是 i<twoIndex即可
#              点2 当nums[i]==2 同样是因为把nums[--twoIndex]的一个未遍历的元素交换到了nums[i], 所以i不自增，就是为了遍历这个交换到此处但是还没有遍历的元素;
# 就是荷兰国旗问题
#三指针p0 p2 curr
#p0和curr指向开头0   p2=n-1
# while curr<=p2:
# curr如果踩到0，则和p0交换，curr和p0都向右移动
# curr踩到2，则和p2交换，都向右移动
#没有踩到0,2,那curr自己向右移动



In [2]:
# def a(b,x=[1],c=3):
#     print('停止标志位',b)
#     print('存储:',x)
#     print('c:',c)
#     c+=1
#     b=b-1
#     if b==0:
#         return 1
#     x[0]+=1
#     a(b,x)
# 两个一样，有无默认一样

def a(b,x,c=3):
    print('停止标志位',b)
    print('存储:',x)
    print('c:',c)
    c+=1
    b=b-1
    if b==0:
        return 1
    x[0]+=1
    a(b,x)
a(5,[1])
# 在递归中，x常作为一个状态存储单位，也就是不管有多少层递归，大家都是共享这个x[]的
# 只有数组才有充当 全局状态存储的功能，单个数字不行，例如这里的c
# 最好用字典来存 

停止标志位 5
存储: [1]
c: 3
停止标志位 4
存储: [2]
c: 3
停止标志位 3
存储: [3]
c: 3
停止标志位 2
存储: [4]
c: 3
停止标志位 1
存储: [5]
c: 3


In [63]:
a={1:2}
if 1 in a.keys():
    print('有')

有


In [18]:
# 455 分发饼干
# 尽可能先满足可以满足的
# 假设饼干1，只能满足1，那就不管2,3.  如果饼干3,   能满足1，那也先给1
# 所以算法是：有恰好匹配的优先，然后再找稍微比这个饼小一点的小孩
child=[1,1,3]
# 可以用桶排序
# 贪心算法
gift=[1,1]
class Solution:
    def findContentChildren(self, g, s):
        g=sorted(g)
        s=sorted(s)#快排序
        cnt_g=0
        cnt_s=0
        while cnt_g<len(g) and cnt_s < len(s):
            if g[cnt_g]<=s[cnt_s]: 
                cnt_g+=1# 满足第一个孩子为主  ，如果不满足，一定要找到满足的饼干为止 ，因为连这个最小的孩子都满足不了的话，后面那些更加满足不了
            cnt_s+=1# 遍历礼物
        return cnt_g #返回可以满足孩子的数量  


a=Solution()
a.findContentChildren(child,gift)


2

In [19]:
# 求根号二，二分法
import math
class Solution:
    def mySqrt(self, x): #求根号2
        left=0
        right = math.ceil(x / 2)
        print(right)
        while left<=right:
            mid = left + (right - left) //2
            tmp = mid * mid  #取出中点做平方
            print('tmp值：',tmp)
            if tmp==x:
                return mid
            elif tmp<x:
                left=mid+1
            else:
                right =mid-1
        return right 
        
        
exam=Solution()
exam.mySqrt(16)

8
tmp值： 16


4

In [44]:
# 为算法表达式设计优先级
class Solution:
    def diffWaysToCompute(self, input):
        return_list=[]
        for i in range(len(input)): 
            c=input[i] #取出第i个字符，如果找到的是操作符号，则左右两边进入递归
            print(c)
            if c in ['+','-','*','/']:
                left=self.diffWaysToCompute(input[:i])
                right=self.diffWaysToCompute(input[i+1:])
                for l in left:
                    for r in right:
                        if c=='+':
                            return_list.append(l+r)
                        elif c=='-':
                            return_list.append(l-r)
                        elif c=='*':
                            return_list.append(l*r)
        if not return_list: #左边或者右边已经没东西了
                return_list.append(int(input)) #那就返回这个数
        return return_list
            
nums='2+3*4'
exam=Solution()
exam.diffWaysToCompute(nums)

2
+
2
3
*
3
4
4
3
*
2
+
2
3
3
4
4


[14, 20]

In [27]:
a={'a':1}
if a.get('a',0):
    print('进入')


进入


In [29]:
def example(x):
    
    print(x)

    if x!=0:
        example(x-1)
example(8)

8
7
6
5
4
3
2
1
0


In [35]:
nums=[]
if not nums: #空的话为none
    print('ok')

ok


In [4]:
import torch 
import numpy as np
from torch.autograd import Variable

In [30]:
tensor1 = torch.Tensor(np.array([[0.3,0.7],[0.9,0.1],[0.2,0.8]]))   
var=Variable(tensor1, requires_grad=True)
var

tensor([[0.3000, 0.7000],
        [0.9000, 0.1000],
        [0.2000, 0.8000]], requires_grad=True)

In [33]:
np1=var.data.numpy()
np1

array([[0.3, 0.7],
       [0.9, 0.1],
       [0.2, 0.8]], dtype=float32)

In [13]:
np2=np1[:,1]
np2

array([0.7, 0.6, 0.8], dtype=float32)

In [19]:
np1.mean(axis=1)

array([0.5, 0.5, 0.5], dtype=float32)

In [23]:
np3=np.mean(np1,axis=0)
np3

array([0.3, 0.7], dtype=float32)

In [36]:
np.argmax(np3,axis=0)

1

In [1]:
#160
class Solution(object):
    def getIntersectionNode(self, headA, headB): # 从A,B节点走，什么时候相交
        if headA is None or headB is None:
            return None
        L1=headA
        L2=headB
        
        while L1!=L2:
            if L1 :#检测反向
                L1=L1.next
            else:#检查同向关系
                L1=headB
            if L2:
                L2=L2.next
            else:
                L2=headA
        return L1
                
        
        
        

In [2]:
# 232 栈实现队列
class MyQueue(object):

    def __init__(self):
        """
        Initialize your data structure here.
        """
        

    def push(self, x):
        """
        Push element x to the back of queue.
        :type x: int
        :rtype: None
        """
        

    def pop(self):
        """
        Removes the element from in front of queue and returns that element.
        :rtype: int
        """
        

    def peek(self):
        """
        Get the front element.
        :rtype: int
        """
        

    def empty(self):
        """
        Returns whether the queue is empty.
        :rtype: bool
        """



In [8]:
# 1 两数之和
class MyQueue(object):
    def twoSum(self,nums,target):
        dic={}
        for i in range(len(nums)):# 遍历列表
            if target-nums[i] in dic:
                print('发现这个',nums[i])
                print( [dic[target-nums[i]],i])  #dic里面存着读过的元素
            dic[nums[i]]=i # dic[元素]=第i个位置


nums=[1,2,3,4,5,6,7]
exam=MyQueue()
exam.twoSum(nums,8)


发现这个 5
[2, 4]
发现这个 6
[1, 5]
发现这个 7
[0, 6]


In [1]:
# 232 栈实现队列

class MyQueue:
    def __init(self):
        self.stack_in=[]
        self.stack_out=[]
    def push(self,x=None):#输入整数
        self.stack_in.append(x)# [[原来的],[要进来的]]  #这个队列从右边进序列，从右边出一个元素
    def pop(self):
        if self.stace_out:#输出缓存非空
            return self.stack_out.pop() #丢出最右边一个
        else:
            while self.stack_in:#输出缓存没东西，那就把输入缓存放到输出缓存
                self.stack_out.append(self.stack_in.pop())#不断从输入队列的右边提取
            return self.stack_out.pop() 
    def peek(self):#整数
        if self.stack_out: #有东西，就输出最后一个，且保留原有
            return self.stack_out[-1]
        else:
            while self.stack_in:
                self.stack_out.append(self.stack_int.pop())#如果out没有东西，那就一直把in的右边拿进来
            return self.stack_out[-1]
    def empty(self):#bool型 
        return not self.stack_in and not self.stack_out
    

3

In [ ]:
#上题简化版
.append(x)
.pop(0)
stack[0]
return stack==[]


In [25]:
# 409 最长回文串
class Solution:
    def longestPalindrome(self, s):
        k = len(s)
        olist = [0] * k
        nList = [0] * k
        logestSubStr = ""
        logestLen = 0
 
        for j in range(0, k):
            for i in range(0, j + 1):
                if j - i <= 1:
                    if s[i] == s[j]:
                        nList[i] = 1
                        len_t = j - i + 1
                        if logestLen < len_t:
                            logestSubStr = s[i:j + 1]
                            logestLen = len_t
                else:
                    if s[i] == s[j] and olist[i+1]:
                        nList[i] = 1
                        len_t = j - i + 1
                        if logestLen < len_t:
                            logestSubStr = s[i:j + 1]
                            logestLen = len_t
            olist = nList
            nList = [0] * k
        return len(logestSubStr)
 
        
        
nums='abccccdd'
exam=Solution()
exam.longestPalindrome(nums)
        
#这个答案没有考虑头尾是可以循环的

        
        

4

In [33]:
#这是这道题是不用考虑顺序问题的，给出的字符串相当于一个字符集和
import math
#字典统计每个字符出现的个数，每个字符有偶数个就可以用来构成回文
#最中间的字符可以单独出现 所以单独出现的字符放中间

class Solution:
    def longestPalindrome(self, s):
        cnts={}
        for c in s:#把字符出现的次数统计到cnts计数器
            cnts[c]=cnts.get(c,0)+1
        palindrome=0
        for (key,value) in cnts.items():#取出统计字典 
            palindrome+=math.floor(value/2)*2  #返回数字的下舍整数 其实用int就可以了  加上偶数个
        if palindrome<len(s):
            palindrome+=1
        return palindrome
        
        
        
        
        

In [30]:
2&1 #维运算


0

In [37]:
math.floor(3.8),int(3.8)

(3, 3)

In [23]:
# 260 只出现一次数字
# 这个属于位运算
# 普通方法
#这种方法虽然很快，但内存占了很多
nums=[1,2,3,1,2]
class Solution(object):
    def singleNumber(self, nums):
        dic1={}
        for i in range(len(nums)):
            dic1[nums[i]]=dic1.get(nums[i],0)+1
        result=[]
        
        for m,n in dic1.items():
            if n==1:
                result.append(m)
        return result
exam=Solution()
exam.singleNumber(nums)

[3]

In [64]:
nums=[1,2,3,1,2,5]
#这种方法更快，内存消耗更少
#位运算  ^异或  &求与  任何元素异或他自己都等于0   如果整个数组内，按顺序前后异或完，最终的结果刚好是那个出现一次的数字，因为出现过两次的都被抵消了


diff=0
for num in nums:
    diff=diff ^ num #把全部元素放上车，出现两次的，自己下车
print(bin(diff))
diff=diff & (-diff)#负数的二进制，就是原码求反，然后取1  意思就是，反码的时候，前面的0都变成1，然后加1，导致进位到原码的第一个1的位置，
#这两个只出现一次的数，在最低的位置上，绝对一个是1，另一个数是0，这样才异或出1

print(bin(diff))
ret=[0,0]
for num in nums:
    if(diff & num==0): #现在的diff 是在原来diff第一个1出现的位置上有1，其他位置都为0，这里求与，看看遍历的这个数在这个位置上是否为1
        ret[0]=ret[0]^num  #其中一个数，也就是最低位为1的那个数，所可能在的堆,然后在这个堆再次取异或，这次全部数异或完之后，
        #就等于只有一次出现的那个了
    else:
        ret[1]=ret[1]^num #最低位非0的那个数所在堆，自己求异或
ret

0b110
0b10


[5, 3]

In [ ]:
#启发 就是位运算的效率很高

In [46]:
1^1,2^1^1

(0, 2)

In [32]:
2^3^1^1  #这里是等于2^3的

1

In [45]:
2^3,(2^3)^(-(2^3))&2,(2^3)^(-2^3)&3    #可以看出中途异或偶数次的，相当于没有参与过异或，那怎么把他拆开呢

(1, 3, 0)

In [63]:
(3&(-3)),bin(1)#这里的负数自动取反码和加1

(1, '0b1')

In [4]:
# 转化为7进制数
num=14
class Solution(object):
    def convertToBase7(self, num):
        if num==0:
            return 0
        res=""
        is_neg=num<0
        if num<0:
            num=-num#先转为正数
        while num>0:
            res+=str(num%7)
            num//=7
        res=res[::-1] #
        if is_neg:
            res="-"+res
        return res
        
exam=Solution()
exam.convertToBase7(num)




'20'

In [5]:
a=[1,2,3]
a[::-1]

[3, 2, 1]

In [ ]:
# # 树 递归110
class Solution(object):
    def isBalanced(self, root): #递归看是否左子树等于右子树
        1.判断是否到末端 或 一开始就空
        2.进入循环 isBalanced()
        3. 非端点要干嘛 

# 


In [1]:
a=[1,2,3,4]
for i,j in enumerate(a):
    print(i,j)

0 1
1 2
2 3
3 4


In [ ]:
#
def 遍历所有节点
    获得根
    是末端返回1
    
    中间层: 把下一个孩子当做根，给递归，当做表层
    表层：返回左子树和右子树是否相等，相等为true(因为return 会屏蔽掉最后面的)
    
    
def 
    拿到一个子树
    遇到端点 return 1
    
    
    左高度=递归，左子树
    右高度递归，右子树
    return 最大（左，右）
    
    
    

In [35]:
class Solution(object):
    def isBalanced(self, root):
        if root is None:
            return True 
        left=self.getHeight(root.left)
        right=self.getHeight(root.right)
        if abs(left-right)>1:
            return False
        return self.isBalanced(root.left) and self.isBalanced(root.right)  
        
    def getHeight(self,root):
        if root is None:
            return 0
        left=self.getHeight(root.left)
        right=self.getHeight(root.right)
        #如果这里return max(深度(left),深度(right))+1这样会慢一点
        return max(left,right)+1 #不明白+1 如果底部返回1，这里不加1呢 不行  因为这里不加1，相当于没有积累高度

In [ ]:
# 递归分析过程
# 1
def 是否平衡(根)
    return 左子树平衡  and 右子树平衡
如何获得左根深度呢
def 求深度(根):
    return max(左高度,右高度)+1

In [ ]:
# 2细化
def 是否平衡(根)
    return 是否平衡(左) and 是否平衡(右)
如何获得左根深度呢
def 求深度(根):
    return max(求深度(左),求深度(右))+1

In [ ]:
# 3端点
# 2细化
def 是否平衡(根)
    if 端点 :return 1
    
    if 非端点:
        if 深度(左)==深度(右): return 是否平衡(左) and 是否平衡(右) #若这个节点是平衡，则继续检查左和右
        else: return False  #这个放前面会比较好
        
        
如何获得左根深度呢
def 求深度(根):
    if 端点:return 0  #因为端点的父亲深度应该为1  爷爷应该为2
    
    if 非端点:
        return max(求深度(左),求深度(右))+1

In [ ]:
# 144 前序遍历
def 前序遍历(根):
    res=[]#这个是形参吗  对， 因为每次进入都会新建一个res ，每一层递归中，res都是独立的
    if 端点:
        return 空
    if 非端点:
        res.append(根)#根放在前面所以前序遍历
        res.append(前序遍历(左))
        res.append(前序遍历(右))
        return res

In [6]:
def a(x):
    if x>=5:return 0
    x+=1
    res=[]
    res.append(x)
    print(res)
    a(x)
    print(res)
a(1)

[2]
[3]
[4]
[5]
[5]
[4]
[3]
[2]


In [16]:
class Solution:
    def preorderTraversal(self,root):
        result=[]
        if not root:
            return result
        else:
            result.append(root.val)#先序遍历，所以先放根
            result.extend(self.preorderTraversal(root.left))
            result.extend(self.preorderTraversal(root.right))
            return result

In [17]:
a=[1,2,3]
a+=[2]
a.extend([])
a

[1, 2, 3, 2]

In [19]:
# 513 找树最下面那行的最左边的值
#同一层的，从右到左遍历
class Solution:
    def findBottomLeftValue(self,root):
        q=[root]
        while q:
            root=q.pop(0)
            if root.right:
                q.append(root.right)
            if root.left:
                q.append(root.left)
        return root.val 


In [20]:
#
def 遍历():
    q取得[根]
    当 根不为空：
        弹出一个根
        将右加入q
        将左加入q
        
[1]
[3,2]#pop了1节点  因为1有右节点所以加入3，有左所以加入2
[2,5,4]#查找了右3节点的左右为4,5
[5,4,7,6]
pop了5发现5没有左，右，不工作   直到pop了6(最后一行的左边)，就返回这个数的val

SyntaxError: invalid character in identifier (<ipython-input-20-707e82c46dfb>, line 4)

In [ ]:
# 230 bst 二叉搜索树中第k小的元素
# 二叉搜索树   就是总是 左<根<右

#第一种做法，就是把全部元素按照大小取出
#第二种方法，中序遍历，先沉到底，+1,倒数第二行再+1就=2,


In [ ]:
#猜想
#def 中序(根):
    result.extend(左子树的集)
    result.append(根)
    result.extend(右子树的集)
    return result

In [ ]:
# 进一步
# def 中序(根)：
    if 端点:
        return [根.val]
    
    if 非端点:
        result=[]
        result.extend(中序(左子树的集))  
        result.append(根)
        result.extend(中序(右子树的集))
        return result
    然后再取出第K个出来

In [ ]:
# 方法二
value全局变量如何做？如果在类里面self.value就可以def之间调用  递归也可以（递归可以理解为不是调用自己，而是调用自己一样的函数）
全局cnt
# def 计算第K个(根，k):
    中序(根,k)
    return value

def 中序(根,k):#带着K递归 其实也可以把k放在全局变量
    
    if 空端点:
        return 
    else 非空端点:
        中序(左)
        self.cnt+1#第一个是末端点   对每个节点，有return返回到本层时候，都会+1
        if self.cnt==k   计数器达到了k次  
            return 左.val
        #到底点之后
        self.cnt+1 #若没有到k 继续找右子树
        中序(右)

In [ ]:
class Solution:
    def kthSmallest(self,root,k):
        self.cnt,self.val=0,0
        self.inOrder(root,k)
        return self.val
    def inOrder(self,root,k):
        if not root:
            return 
        self.inOrder(root.left,k)
        self.cnt+=1
        if self.cnt==k:
            self.val=root.val
            return
        self.inOrder(root.right,k)

    

In [ ]:
# 208 前缀树

clase node(self):
    self.children={} #每个节点都有个字典装孩子
    node.is_leaf=False   #初始为非叶子



class trie:
    def __init__(self):# 建立一棵树的时候，先建立一个根节点
        self.root=Node()
        
    def 将字符串插入到树中(self,word)：
        node取得根
        for c in 遍历word:
            如果第一个字符在node的孩子中没有出现，则把新根节点赋值给根节点的孩子字典中 第一字符:新建节点
            根换到第一个字符所对的节点
        node.is_leaf=True   #遍历到最后的节点，则令这个节点为叶子节点
    def 查找是否存在此字符串():  #要么中途就没有匹配到，要么匹配完了条件字符串，却还没到树叶节点
        node=self.根
        c 遍历条件字符串
            c在 当前节点的孩子字典里
                node=c在孩子字典里对应的节点
                
            不在:
                return false #中途没匹配到
        遍历完后，看看node.is_leaf()  #若是叶子节点，那就是整个字符串都匹配上了
        
    def 查找是否前缀匹配():#不需要一直匹配到叶子节点   认为 abcdef 也含有abc
        跟上面一样
        遍历完后，直接return true

        
        

In [ ]:
# 785 判断二分图


In [3]:
a=[1,2,3]
list.reverse(a)
a

[3, 2, 1]

In [ ]:
###  关于序列

In [26]:
# 583  字符序列

class Solution():
    def minDistance(self,word1,word2):
        m=len(word1)
        n=len(word2)
        dp=[[0]*(n+1) for _ in range(m+1)]   #表格法
        for i in range(1,m+1):
            for j in range(1,n+1):
                if word1[i-1]==word2[j-1]:  #如果两个符号相同，则+1，再找左上角的最佳匹配长度
                    dp[i][j]=dp[i-1][j-1]+1
                else:
                    dp[i][j]=max(dp[i][j-1],dp[i-1][j])  #如果不匹配，就只删除一个字符，左或者上的最佳匹配
        return dp[m][n]

In [22]:
b=[[0]*3]*4
b
b[2][2]


0

In [27]:
a=Solution()
a.minDistance("abcdefg","bdg")

3

In [32]:
## 300   数字序列
# 最长的递增序列长度
class Solution:
    def lengthOfLIS(self,nums):
        if len(nums)==0:
            return 0
        LIS=[1]*len(nums)
        for i in range(1,len(nums)):#i是右指针，j是左指针
            LIS[i]=max([1+LIS[j] for j in range(i) if nums[j]<nums[i]] +1) #对于每个i，都要和前面i-1个比较，而不是只和小于自己的比较，
        #可以设置从i开始，右到左扫，遇到小于i数的，就用它来+1就够了，
        return max(LIS)


In [ ]:
# 416  背包分割等和子集
#如果可以分割，则返回true
# 背包总容量，就是相等的和 这个值
class Solution:
    def canPartition(self,nums):
        c=sum(nums)
        if c






