In [1]:
from sklearn import preprocessing
import numpy as np
a=np.array([[10,2.7,3.6],[100,1,2],[120,20,40]])
print('标准化前:',a)
print('标准化后:',preprocessing.scale(a))


标准化前: [[ 10.    2.7   3.6]
 [100.    1.    2. ]
 [120.   20.   40. ]]
标准化后: [[-1.39346603 -0.60577157 -0.66102858]
 [ 0.48771311 -0.80381228 -0.75220493]
 [ 0.90575292  1.40958385  1.41323351]]


In [3]:
#交叉验证
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [15]:
iris=load_iris()
X=iris.data
y=iris.target

print(len(X))
print(len(y))
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,)#random_state=None 默认方式下，随机分配，这样每次取都不同数。难以调参，
# =数表示不同方式取数据，最大2^32，表示有这么多种取数据方式，假如设定了random_state=3，那一直都按照3的方式分

print(len(X_train))
print(len(X_test))

150
150
105
45


In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([10,20,30,40,50,60,70,80,90])
X_train,X_test,y_train,y_test=train_test_split(a,b,test_size=0.3,random_state=1)
X_train,X_test,y_train,y_test

(array([8, 2, 1, 5, 4, 6]),
 array([9, 3, 7]),
 array([80, 20, 10, 50, 40, 60]),
 array([90, 30, 70]))

In [7]:
a=[1,2,3,4,5,6,7,8,9]
b=[10,20,30,40,50,60,70,80,90]
X_train,X_test,y_train,y_test=train_test_split(a,b,test_size=0.3,random_state=2)
#这两次分数据，如果设置了random_state，方式一样，则分的数据是完全一样的，而且也达到随机分7:3的目的
X_train,X_test,y_train,y_test

([3, 4, 1, 6, 8, 9], [5, 2, 7], [30, 40, 10, 60, 80, 90], [50, 20, 70])

In [5]:
knn=KNeighborsClassifier(n_neighbors=5)
scores=cross_val_score(knn,X,y,cv=5,scoring='accuracy')
print(scores)#每组评分
print('平均评分:',scores.mean())

[0.96666667 1.         0.93333333 0.96666667 1.        ]
平均评分: 0.9733333333333334


In [7]:
#learning_curve()
#validation_curve()
#from sklearn.externals import joblib #导入自带模型
#joblib.dump(model,sklearn_save/clf.pkl) #保存模型
#model2=joblib.load('sklearn_save/clf.pkl') #重新加载模型



In [53]:
class test:
    def a(x):
        print('进入a')
        def b(x):
            print(x)
        print('过了b')
        b('进了b')
        a()

In [54]:
a=test()
exam=test.a(1)

进入a
过了b
进了b


TypeError: 'test' object is not callable