In [43]:
#《python数据分析》书，pandas部分
import numpy as np
import pandas as pd
import os

In [44]:
path=r'C:\Users\mrliangcb\Desktop\note\extra_feature\test.csv'#遇到逗号算一个列分割，遇到\n转下一行
data = pd.read_csv(path,nrows=None) #names=["a","b","c"]标列名，这里没name就取第一行作为列名字，航标自动设置0~序号
#print(data.head(10))#先看前10个数据

a=pd.Series([1,2,3])
print(a)
a[2]=5
data.loc[[1,2,3],'ID']=data.loc[[1,2,3],'Hand']
print(data)


0    1
1    2
2    3
dtype: int64
               ID M/F Hand  Age  Educ  SES  MMSE  CDR  eTIV   nWBV    ASF  \
0   OAS1_0001_MR1   F    R   74   2.0  3.0  29.0  0.0  1344  0.743  1.306   
1               R   F    R   55   4.0  1.0  29.0  0.0  1147  0.810  1.531   
2               R   F    R   73   4.0  3.0  27.0  0.5  1454  0.708  1.207   
3               R   M    R   28   NaN  NaN   NaN  NaN  1588  0.803  1.105   
4   OAS1_0005_MR1   M    R   18   NaN  NaN   NaN  NaN  1737  0.848  1.010   
5   OAS1_0006_MR1   F    R   24   NaN  NaN   NaN  NaN  1131  0.862  1.551   
6   OAS1_0007_MR1   M    R   21   NaN  NaN   NaN  NaN  1516  0.830  1.157   
7   OAS1_0009_MR1   F    R   20   NaN  NaN   NaN  NaN  1505  0.843  1.166   
8   OAS1_0010_MR1   M    R   74   5.0  2.0  30.0  0.0  1636  0.689  1.073   
9   OAS1_0011_MR1   F    R   52   3.0  2.0  30.0  0.0  1321  0.827  1.329   
10  OAS1_0012_MR1   M    R   30   NaN  NaN   NaN  NaN  1574  0.842  1.115   
11  OAS1_0013_MR1   F    R   81   5.0  2.0

In [45]:
#建立series
#https://www.baidu.com/link?url=Tw2bA_HzsYklp4OA4Vt0ZTjgn_PFIqVuzPzb7e9lyXvRwi6CdyD7CaZBjFlqAMLUrwPo34MpdR_eJjbpKp6cra&wd=&eqid=8f2c823c0008711a000000065bf2b63c
    
#series，是一种类似于一维数组的，可以由list或者nparray产生。是一种dataframe的列，且没有了列名
#左边是index索引，行标
se=pd.Series([4,3,6,10],index=['a','b','c','d'])
print(a)

0    1
1    2
2    5
dtype: int64


In [46]:
#查看属性
#查看.value，返回np
print(se.values)#df是返回二维的
print(se.index)

[ 4  3  6 10]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [47]:
#索引 二维表示自己类型，一维表示比自己低的类型，如np，    df也一样的。一维的时候只能选一个，二维可以选两个属性
    #优先级list   np  series  pandas
    print(se['a'])
    print(se[['a']])

    
    
    



4
a    4
dtype: int64


In [48]:
#series内运算

#选出value大于0的的series
print(se[se>0])
#se
print(se*2)

a     4
b     3
c     6
d    10
dtype: int64
a     8
b     6
c    12
d    20
dtype: int64


In [49]:
#判断index
panduan='a' in se
print(panduan)

True


In [50]:
#前面是list转series
#现在字典转series，列名为字典键#我称列名=key，作为index的，如果另外设index，则说明只显示这些index，但如果没有重名的话，则会显示nan
#如建立了一个有'liming'索引的series，但后来设置了index作为索引，则不显示liming这条记录，而显示index里面的索引时，无value则nan，如果无设置index
#则默认使用列名作为index,
#series自己的列名优先级最高，其次是自己另外设置的index和column。

se2={'liming':25,'wangwu':35,'xiaoming':19}#series的时候，value只有一个。而dataframe的时候value是一个list
index=['china','wangwu','france']#指的是我要显示的index行标，如果se2的值中没有china，则那个index对应的value=nan
se2=pd.Series(se2,index)
print(se2)


china      NaN
wangwu    35.0
france     NaN
dtype: float64


In [51]:
#查找缺失值
se3={'liming':25,'wangwu':35,'xiaoming':19}
se3=pd.Series(se3)
print(se3,'\n')
print(pd.isnull(se3))#.index.tolist()


liming      25
wangwu      35
xiaoming    19
dtype: int64 

liming      False
wangwu      False
xiaoming    False
dtype: bool


In [52]:
#合并，填充
    #.fillna()  可以是value，或者数组，series

In [53]:
#series修改index
se3.index=['a','b','c']#一下子要全部列名index都写出来
print(se3)
#reindex(上面那个是修改，这里是选择保留什么index的行)
se3.reindex(['a','b'],fill_value=0)

a    25
b    35
c    19
dtype: int64


a    25
b    35
dtype: int64

In [54]:
#接下来是dataframe

#二维矩阵创建df
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
index=['a','b','c']
column=['ming','wang','liang']
df1=pd.DataFrame(a,index=['a','b','c'],columns=column)
print(df1)







#列名在series那里作为index，在df这里就是列名了
#以后习惯用list np series df的优先级顺序思考问题
#'列名':[一列value]
se1=[32,40,19]
se2=[99,100,80]
se3=[2000,1998,1999]
dit={'age':se1,
        'score':se2,
        'birth':se3}
df1=pd.DataFrame(dit,index=['liming','wangwu','xiaoming'])#,columns=[1,2,3]如果加上这个，则不显示字典中的列，因为没有提及字表列名，则显示nan
print(df1)


   ming  wang  liang
a     1     2      3
b     4     5      6
c     7     8      9
          age  score  birth
liming     32     99   2000
wangwu     40    100   1998
xiaoming   19     80   1999


In [26]:
#给行和列名加一个统一的名字
    df1.index.name='name'
    df1.columns.name='data'
    print(df1)
    

data      age  score  birth
name                       
liming     32     99   2000
wangwu     40    100   1998
xiaoming   19     80   1999


In [27]:
#取得二维内容 np
print(df1.values)

[[  32   99 2000]
 [  40  100 1998]
 [  19   80 1999]]


In [28]:
#取出series
print(df1['age'])

name
liming      32
wangwu      40
xiaoming    19
Name: age, dtype: int64


In [29]:
#取出df
print(df1[['age','score']])
print('按照loc取:\n',df1.loc[:,['age','score']])#选正方形区域返回df的最好方法，loc

data      age  score
name                
liming     32     99
wangwu     40    100
xiaoming   19     80
按照loc取:
 data      age  score
name                
liming     32     99
wangwu     40    100
xiaoming   19     80


In [30]:
#index的不可修改性，不能单独修改
#df[]判断和(定位)修改值不能一步做完，要分开



data      age  score
name                
wangwu     40    100
xiaoming   19     80

In [236]:
#对整一个series赋值
#1.赋同一个整数
df1['age']=1
print(df1)

#2.给series赋series或者list，但是长度必须匹配
df1['age']=[32,40,19]
print(df1)

          age  score  birth
liming      1     99   2000
wangwu      1    100   1998
xiaoming    1     80   1999
          age  score  birth
liming     32     99   2000
wangwu     40    100   1998
xiaoming   19     80   1999


In [237]:
#删除列
#del df1['birth']
#print(df1)

In [238]:
#df的index不可以改，而series的可以全改
#index不可改，但可以选择显示的index
#重新改列名
print(df1)
#df1.reindex([1,'xiaoming','liming'])#而且顺序是按照这个的

          age  score  birth
liming     32     99   2000
wangwu     40    100   1998
xiaoming   19     80   1999


In [239]:
#df改变columns
df1.reindex(columns=[1,'xiaoming','liming'])

1  xiaoming  liming
liming   NaN       NaN     NaN
wangwu   NaN       NaN     NaN
xiaoming NaN       NaN     NaN

In [240]:
print(df1)

          age  score  birth
liming     32     99   2000
wangwu     40    100   1998
xiaoming   19     80   1999


In [230]:
#ix是最简洁的索引功能
df1.ix[['liming'],['age']]
print(df1)


#单个或者批量修改dataframe的value
#data.ix[['liming','wangwu'],['age','birth']]#先行，后列
#然后可以修改值  df1.ix[['liming'],['age']]=22  可以批量改,整个series改：df1[['age']]=22
#批量修改


          age  score  birth
liming     22     99   2000
wangwu     22    100   1998
xiaoming   22     80   1999


c:\lcb\py367\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [207]:
#看到p208页